version: '3'
services:
  nginx:
    container_name: nginx
    image: envrideRegistry.azurecr.io/nginx:latest
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY_FRONTEND}
    ports:
      - 80:80
      - 443:443

  maps:
    container_name: maps
    image: envrideRegistry.azurecr.io/maps:latest
    restart: always
    build:
      context: ./map-service
      dockerfile: ./Dockerfile
      args:
        GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY_BACKEND}
    expose:
      - "8090"